FROM node:16
WORKDIR /app

# Setup proxy to API used in saleor-platform
RUN apt-get update && apt-get install -y nginx
COPY ./nginx/dev.conf /etc/nginx/conf.d/default.conf

# Setup pnpm
RUN curl -f https://get.pnpm.io/v6.16.js | node - add --global pnpm

COPY package*.json pnpm-lock.yaml ./
RUN pnpm install
COPY . .
ARG API_URI
ENV API_URI ${API_URI:-http://localhost:8000/graphql/}
ENV NEXT_TELEMETRY_DISABLED 1

EXPOSE 3001
CMD pnpm dev -- --hostname 0.0.0.0
